BOSA21Q1-796 Ability to add two subtitles outside of <h1> in home page
belighted/bosa-cities pull request #122
Opened 2022-05-08 08:23 UTC by ThomasCollignon

[BOSA21Q1-796](https://belighted.atlassian.net/browse/BOSA21Q1-796)

This dev would require these admin updates:

- In (EN) Settings > Homepage > Hero image > Welcome text (_(NL) Instellingen > Startpagina > Hero-afbeelding > Welkom tekst_), keep only the first part.
- Add these translations
  - decidim.pages.home.hero.subtitle-1
  - decidim.pages.home.hero.subtitle-2
  - decidim.pages.home.hero.subtitle-2-assemblies
- CSS custom

2022-05-08 09:29 UTC, sergei-krylov requested changes
While it's fine for NS case as it is temporary platform, I would still suggest to fix those things, it's quick to do.
Mainly because it might produce a typo in translation for admins as these keys are in different format, so they might mistype `_` (as usual) instead of `-`.
Same for html class names - that's the common convention to use dashes in ids and classes.

For future devs overall - let's stick with the same format as other existing classes, translation keys, etc.
Thanks!

2022-05-08 09:29 UTC, sergei-krylov commented on app/cells/decidim/content_blocks/hero/show.erb
> +    <div id="home-page-subtitle-1" class="row section.hero hero-heading">
Class names delimiter should be `-` instead of `.`
`section.hero` -> `section-hero`

2022-05-08 09:29 UTC, sergei-krylov commented on app/cells/decidim/content_blocks/hero/show.erb
> +      <span><%= t("decidim.pages.home.hero.subtitle-2",
Translation keys are in snake case, delimiter should be `_` instead of `-`
`decidim.pages.home.hero.subtitle-2` -> `decidim.pages.home.hero.subtitle_2`
`decidim.pages.home.hero.subtitle-2-assemblies` -> `decidim.pages.home.hero.subtitle_2_assemblies` - this one could be also a `subtitle_2_assemblies_link_text` to be more precise.

2022-05-09 06:25 UTC, ThomasCollignon commented on app/cells/decidim/content_blocks/hero/show.erb
> +    <div id="home-page-subtitle-1" class="row section.hero hero-heading">
It shouldn't even be here, removed.

2022-05-09 06:26 UTC, ThomasCollignon commented on app/cells/decidim/content_blocks/hero/show.erb
> +      <span><%= t("decidim.pages.home.hero.subtitle-2",
No problem, changed.

2022-05-09 07:24 UTC, sergei-krylov approved these changes
Nice! Thank you!

2022-05-09 08:28 UTC, simon-lejeune approved these changes

2022-05-09 08:33 UTC, merged